# Project information
site_name: 'DiyBCI - DoItYourself BCI'
site_description: 'Nuestro cuaderno de viaje navegando por las profundas aguas de la neurociencia.'
site_author: 'NeuroTeam - Machine Learning Hispano'
site_url: 'https://DeftWork.github.io/DiyBCI/'

# Repository
repo_name: 'DeftWork/DiyBCI'
repo_url: 'https://github.com/DeftWork/DiyBCI'

# Copyright
copyright: 'Copyright &copy; 2019 NeuroTeam MLH'

# Configuration
theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Avoid collision with gh-pages
docs_dir: 'mkdocs'
site_dir: 'docs'
# Query string example
edit_uri: edit/master/mkdocs/

# Customization
extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
    
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/ml-hispano'
    - type: 'twitter'
      link: 'https://twitter.com/MLHispano'
    - type: 'slack'
      link: 'https://bit.ly/2Oqingj'

# Google Analytics
google_analytics:
  - 'UA-139487885-2'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

